clean:
	rm -rf 1_CppGrundlagen/*.exe
	rm -rf 1_CppGrundlagen/*.o
	rm -rf 1_Programmieraufgabe/*.exe
	rm -rf 1_Programmieraufgabe/*.o
	rm -rf 2_ArrayPointer/*.exe
	rm -rf 2_ArrayPointer/*.o
	rm -rf 2_Programmieraufgabe/*.exe
	rm -rf 2_Programmieraufgabe/*.o
	rm -rf 3_Programmieraufgabe/*.exe
	rm -rf 3_Programmieraufgabe/*.o
	rm -rf 3_WeitereGrundlagen/*.exe
	rm -rf 3_WeitereGrundlagen/*.o
	rm -rf 4_Programmieraufgabe/*.exe
	rm -rf 4_Programmieraufgabe/*.o
	rm -rf 4_STLVector/*.exe
	rm -rf 4_STLVector/*.o
	rm -rf 5_STLString/*.exe
	rm -rf 5_STLString/*.o
	rm -rf 6_Programmieraufgabe/*.exe
	rm -rf 6_Programmieraufgabe/*.o
	rm -rf 6_STLContainerIterator/*.exe
	rm -rf 6_STLContainerIterator/*.o
	rm -rf 7_Programmieraufgabe/*.exe
	rm -rf 7_Programmieraufgabe/*.o
	rm -rf 7_STLAlgorithmen/*.exe
	rm -rf 7_STLAlgorithmen/*.o
	rm -rf 8_Objektorientierung/*.exe
	rm -rf 8_Objektorientierung/*.o
	rm -rf 8_Programmieraufgabe/*.exe
	rm -rf 8_Programmieraufgabe/*.o
	rm -rf 9_Programmieraufgabe/*.exe
	rm -rf 9_Programmieraufgabe/*.o
	rm -rf 9_TemplatesOperator/*.exe
	rm -rf 9_TemplatesOperator/*.o
	rm -rf 10_LambdaFunktionen/*.exe
	rm -rf 10_LambdaFunktionen/*.o
	rm -rf 10_Programmieraufgabe/*.exe
	rm -rf 10_Programmieraufgabe/*.o
	rm -rf 11_MoveCopy/*.exe
	rm -rf 11_MoveCopy/*.o
	rm -rf 11_Programmieraufgabe/*.exe
	rm -rf 11_Programmieraufgabe/*.o
	rm -rf 12_Programmieraufgabe/*.exe
	rm -rf 12_Programmieraufgabe/*.o
	rm -rf 12_SmartPointer/*.exe
	rm -rf 12_SmartPointer/*.o
	rm -rf 13_ThreadsExceptions/*.exe
	rm -rf 13_ThreadsExceptions/*.o
	rm -rf 14_AdvancedCppFeatures/*.exe
	rm -rf 14_AdvancedCppFeatures/*.o
	rm -rf Computerspiel1/*.exe
	rm -rf Computerspiel1/*.o
	rm -rf Computerspiel2/*.exe
	rm -rf Computerspiel2/*.o
	rm -rf Computerspiel3/*.exe
	rm -rf Computerspiel3/*.o
	rm -rf Computerspiel4/*.exe
	rm -rf Computerspiel4/*.o
	rm -rf Computerspiel5/*.exe
	rm -rf Computerspiel5/*.o
	rm -rf Computerspiel5/*.exe
	rm -rf Programmierprojekt1/*.o
	rm -rf Programmierprojekt1/*.exe
	rm -rf Programmierprojekt2/*.o
	rm -rf Programmierprojekt2/*.exe
	rm -rf Programmierprojekt3/*.o
	rm -rf Programmierprojekt3/*.exe
	rm -rf Programmierprojekt4/*.o
	rm -rf Programmierprojekt4/*.exe
	rm -rf ZusatzaufgabeStrings/*.o
	rm -rf ZusatzaufgabeStrings/*.exe

.phony: clean
